FROM golang:1.26.5-bookworm AS build

WORKDIR /code/

COPY go.mod go.sum /code/
RUN go mod download

COPY . /code/

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o cover-utamita-bot

RUN install -d -m 0755 /out/app && \
  install -m 0755 /code/cover-utamita-bot /out/app/cover-utamita-bot

FROM gcr.io/distroless/static-debian13:nonroot

COPY --from=build --chown=nonroot:nonroot /out/app /app

WORKDIR /app

USER nonroot:nonroot

EXPOSE 80

CMD ["/app/cover-utamita-bot"]
